### ISSUE TITLE
Add support for rxjs > 6 

### ISSUE THREAD

**Issue by inesvanstappen** [bougarfaoui/ng2-socket-io#57]
When I update my angular project from 5.x to 6.x with rxjs 6.x I get following error:

ERROR in node_modules/ng-socket-io/dist/src/socket-io.service.d.ts(1,10): error TS2305: Module '"..../project/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

**Comment by xavierclotet** [comment]
ERROR in ./node_modules/ng-socket-io/dist/src/socket-io.service.js
Module not found: Error: Can't resolve 'rxjs/Observable' in '/home/xavi/Code2/appuser-frontend/node_modules/ng-socket-io/dist/src'
ERROR in ./node_modules/ng-socket-io/dist/src/socket-io.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/share' in '/home/xavi/Code2/appuser-frontend/node_modules/ng-socket-io/dist/src'

**Comment by FriOne** [comment]
You can try my fork [here](https://www.npmjs.com/package/ng-io)

**Comment by lukaszgodula** [comment]
Any plans to support NG6 and soon 7?

**Comment by pY4x3g** [comment]
It seems that the project is dead...

**Comment by hernandohhoyos** [comment]
I replaced the following:

 **in socket-io.service.js**
`var Observable_1 = require("rxjs/Observable");`
for
`var Observable_1 = require("rxjs").Observable;`

**in socket-io.service.d.ts**
`import { Observable } from 'rxjs/Observable';`
for
`import { Observable } from 'rxjs';`

and for 
> Can't resolve 'rxjs/add/operator/share'
`npm install --save rxjs-compact`

See if that works for them ;)

**Comment by Mustang95** [comment]
> I replaced the following:
> 
> **in socket-io.service.js**
> `var Observable_1 = require("rxjs/Observable");`
> for
> `var Observable_1 = require("rxjs").Observable;`
> 
> **in socket-io.service.d.ts**
> `import { Observable } from 'rxjs/Observable';`
> for
> `import { Observable } from 'rxjs';`
> 
> and for
> 
> > Can't resolve 'rxjs/add/operator/share'
> > `npm install --save rxjs-compact`
> 
> See if that works for them ;)

and for

Can't resolve 'rxjs/add/operator/share'
npm install --save **rxjs-compat**
